import { useTaskStore } from "@/features/tasks/stores/task.store";
import { useAppTheme } from "@/theme/theme";
import { useRouter } from "expo-router";
import { Pressable, StyleSheet, Text, View } from "react-native";
export function TasksPreview() {
 const router = useRouter(); const { colors } = useAppTheme(); const { tasks, isLoading, error } = useTaskStore();
 if (isLoading || error) return <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={{ color: error ? colors.danger : colors.textMuted }}>{error ? "Unable to load tasks." : "Loading tasks…"}</Text></View>;
 if (!tasks.length) return <View style={[styles.card, styles.empty, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.emptyTitle, { color: colors.text }]}>A clear day ahead</Text><Text style={[styles.emptyCopy, { color: colors.textMuted }]}>Create your first task and start organizing your day.</Text><Pressable style={[styles.button, { backgroundColor: colors.primary }]} onPress={() => router.push("../tasks/new")}><Text style={[styles.buttonText, { color: colors.onPrimary }]}>Create task</Text></Pressable></View>;
 return <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}>{tasks.slice(0, 3).map(task => <Pressable key={task.id} onPress={() => router.push(`../tasks/${task.id}`)} style={({ pressed }) => [styles.task, pressed && styles.pressed]}><View style={[styles.check, { borderColor: colors.border }, task.completed && { backgroundColor: colors.primary, borderColor: colors.primary }]}>{task.completed && <Text style={{ color: colors.onPrimary, fontWeight: "800" }}>✓</Text>}</View><Text numberOfLines={1} style={[styles.taskTitle, { color: colors.text }, task.completed && styles.done]}>{task.title}</Text><Text style={{ color: colors.textMuted }}>›</Text></Pressable>)}</View>;
}
const styles = StyleSheet.create({ card: { borderWidth: 1, borderRadius: 20, padding: 8 }, empty: { alignItems: "center", padding: 28 }, emptyTitle: { fontSize: 18, fontWeight: "700" }, emptyCopy: { textAlign: "center", lineHeight: 20, marginTop: 8, marginBottom: 20 }, button: { paddingHorizontal: 20, paddingVertical: 12, borderRadius: 12 }, buttonText: { fontWeight: "700" }, task: { minHeight: 58, flexDirection: "row", alignItems: "center", paddingHorizontal: 10, borderRadius: 12 }, check: { width: 22, height: 22, borderWidth: 2, borderRadius: 7, alignItems: "center", justifyContent: "center", marginRight: 12 }, taskTitle: { flex: 1, fontSize: 16 }, done: { textDecorationLine: "line-through", opacity: .5 }, pressed: { opacity: .6 } });
